Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/local/Cellar/certbot/0.8.1/libexec/lib/python2.7/site-packages/certbot/main.py", line 717, in main
    setup_logging(config, _cli_log_handler, logfile='letsencrypt.log')
  File "/usr/local/Cellar/certbot/0.8.1/libexec/lib/python2.7/site-packages/certbot/main.py", line 630, in setup_logging
    config, logfile=logfile, fmt=fmt)
  File "/usr/local/Cellar/certbot/0.8.1/libexec/lib/python2.7/site-packages/certbot/main.py", line 599, in setup_log_file_handler
    raise errors.Error(msg.format(log_file_path))
Error: Access denied writing to /var/log/letsencrypt/letsencrypt.log. To run as non-root, set --logs-dir, --config-dir, --work-dir to writable paths.
